### ISSUE TITLE
有之前的版本吗

### ISSUE THREAD

**Issue by Ericliu68** [qingshuisiyuan/electron-ssr-backup#4]
0.2.4的版本苹果的

**Comment by qingshuisiyuan** [comment]
保存了0.2.6,0.2.5,没有0.2.4的好像

**Comment by Ericliu68** [comment]
坐等你linux配置教程，因为我ubuntu18.04的也用不了0.2.6

**Comment by Ericliu68** [comment]
我想贡献一下我的0.2.4的deb的，希望楼主能接受

**Comment by qingshuisiyuan** [comment]
> 我想贡献一下我的0.2.4的deb的，希望楼主能接受

因为我在多个linux发行版上稍微配置一下几乎没有问题，我还是希望用0.2.6版本的

**Comment by Ericliu68** [comment]
好的，等你的教程

**Comment by Ericliu68** [comment]
楼主写一下windows的配置教程吧，我的windows一直不成功

**Comment by qingshuisiyuan** [comment]
> 楼主写一下windows的配置教程吧，我的windows一直不成功

虚拟机manjaro写到一半，挂了。。。
Windows最好用原版，我自己都用的原版.net.exe

**Comment by Leonliu12138** [comment]
请问下哪里有win系统原版的吗？

**Comment by Leonliu12138** [comment]
请问下哪里有win系统原版的吗？

**Comment by Ericliu68** [comment]
> 请问下哪里有win系统原版的吗？

https://github.com/shadowsocks/shadowsocks-windows/releases，最近发现新工具，brook，同样支持shadowocks，链接发给你https://github.com/txthinking/brook/releases，我用的是20190205版的Brook.exe
