### ISSUE TITLE
[error] http proxy server connect error: Error: Socket Closed

### ISSUE THREAD

**Issue by qinggeng2015** [qingshuisiyuan/electron-ssr-backup#9]
ubuntu 18.04 报错，[error] http proxy server connect error: Error: Socket Closed
google搜索的时候检索到原作者的issue中有这个问题，但是已经404了，求助！

**Comment by qingshuisiyuan** [comment]
网页快照试试？
https://github.com/qingshuisiyuan/electron-ssr-backup/blob/master/Ubuntu.md
或许会帮到你

**Comment by qinggeng2015** [comment]
只能在google上搜索到，不能在百度中搜到，google好像沒提供快照功能

**Comment by qinggeng2015** [comment]
怀疑是pac的问题，使用SwitchyOmega作代理切换后正常使用

**Comment by wangbm** [comment]
请问楼主如何解决问题的

**Comment by qinggeng2015** [comment]
使用Shadowsocks-qt5建立连接，使用Chrome插件SwitchyOmega切换代理
@bingqwq
